services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hr_backend
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    networks:
      - hr_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hr_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - hr_network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000

networks:
  hr_network:
    driver: bridge
