/* Create public schema tables and relationships */

/* Departments */
CREATE TABLE public.departments (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL UNIQUE,
    description text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

/* Employees */
CREATE TABLE public.employees (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL,
    email varchar NOT NULL UNIQUE,
    role varchar,
    department_id integer REFERENCES public.departments(id),
    phone_number varchar,
    address text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

/* Attendances */
CREATE TABLE public.attendances (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id integer REFERENCES public.employees(id),
    attendance_date date NOT NULL,
    status varchar,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    check_in_time timestamp without time zone,
    check_out_time timestamp without time zone,
    notes text
);

/* Leave Balances */
CREATE TABLE public.leave_balances (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id integer REFERENCES public.employees(id),
    year integer NOT NULL,
    total_days integer NOT NULL,
    days_used integer NOT NULL
);

/* HR Policies (vector column for embeddings) */
CREATE EXTENSION IF NOT EXISTS vector;  -- ensure vector extension
CREATE TABLE public.hr_policies (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    document_name varchar NOT NULL,
    chunk_text text NOT NULL,
    embedding vector(384)
);

/* Leave Requests */
CREATE TABLE public.leave_requests (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id integer REFERENCES public.employees(id),
    leave_date date NOT NULL,
    reason text,
    status varchar DEFAULT 'pending'
);

/* Task Groups */
CREATE TABLE public.task_groups (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_name varchar NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

/* Task Group Leaders (junction table) */
CREATE TABLE public.task_group_leaders (
    task_group_id integer NOT NULL,
    employee_id integer NOT NULL,
    PRIMARY KEY (task_group_id, employee_id),
    FOREIGN KEY (task_group_id) REFERENCES public.task_groups(id),
    FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);

/* Tasks */
CREATE TABLE public.tasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_group_id integer REFERENCES public.task_groups(id),
    task_title varchar NOT NULL,
    location varchar,
    expected_days integer,
    priority varchar DEFAULT 'Medium',
    notes text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

/* Labours */
CREATE TABLE public.labours (
    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name varchar NOT NULL,
    skill varchar NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

/* Task Labours (junction table) */
CREATE TABLE public.task_labours (
    task_id integer NOT NULL,
    labour_id bigint NOT NULL,
    PRIMARY KEY (task_id, labour_id),
    FOREIGN KEY (task_id) REFERENCES public.tasks(id),
    FOREIGN KEY (labour_id) REFERENCES public.labours(id)
);

/* Documents (vector column for embeddings) */
CREATE TABLE public.documents (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content text NOT NULL,
    metadata jsonb,
    embedding vector(384),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

/* Generated Documents - For PDF document generation tracking */
CREATE TABLE public.generated_documents (
    id varchar(36) PRIMARY KEY, -- UUID for document identification
    employee_id integer REFERENCES public.employees(id) ON DELETE CASCADE,
    document_type varchar(50) NOT NULL, -- service_letter, confirmation_letter, etc.
    file_path text NOT NULL, -- Path to the generated PDF file
    generated_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL, -- When the document expires
    downloaded_at timestamp with time zone, -- When the document was last downloaded
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

/* Enable Row Level Security where applicable */
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_group_leaders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.labours ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_labours ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_documents ENABLE ROW LEVEL SECURITY;

/* Indexes on foreign‑key columns for performance */
CREATE INDEX idx_employees_department_id   ON public.employees(department_id);
CREATE INDEX idx_attendances_employee_id   ON public.attendances(employee_id);
CREATE INDEX idx_leave_balances_employee_id ON public.leave_balances(employee_id);
CREATE INDEX idx_leave_requests_employee_id ON public.leave_requests(employee_id);
CREATE INDEX idx_tasks_task_group_id       ON public.tasks(task_group_id);
CREATE INDEX idx_task_labours_task_id      ON public.task_labours(task_id);
CREATE INDEX idx_task_labours_labour_id    ON public.task_labours(labour_id);
CREATE INDEX idx_generated_documents_employee_id ON public.generated_documents(employee_id);
CREATE INDEX idx_generated_documents_expires_at  ON public.generated_documents(expires_at);
CREATE INDEX idx_generated_documents_type        ON public.generated_documents(document_type);



